### ISSUE TITLE
feature: configure CORS/allow loading website as an iframe for gnosis safe apps

### ISSUE THREAD

**Issue by mikheevm** [yearn/yearn-finance#410]
**Is your feature request related to a problem? Please describe.**
A follow up on: https://github.com/yearn/yearn-finance/pull/400
The Safe wallet needs to be able to access https://yearn.finance/manifest.json but it's currently not possible because CORS is not configured. The Wallet also loads the apps as an iframe but currently, the server doesn't allow to do that

**Describe the solution you'd like**
- Include the following headers for `manifest.json`
```
"Access-Control-Allow-Origin": "*",
"Access-Control-Allow-Methods": "GET",
"Access-Control-Allow-Headers": "X-Requested-With, content-type, Authorization",
```
The PR included that but it doesn't seem to work.
- Allow the website to be loaded as an iframe
Use [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) header instead of `x-frame-options`, with this header you can specify domains to allow the website to be loaded as an iframe, for example:
```
content-security-policy: frame-ancestors https://gnosis-safe.io;
```

**Additional context**
![Screenshot 2021-08-09 at 09 37 04](https://user-images.githubusercontent.com/16622558/128673392-afbd744c-e922-47d1-aa89-195029384a8d.png)
![Screenshot 2021-08-09 at 09 39 27](https://user-images.githubusercontent.com/16622558/128673394-566bf636-da95-4d5d-bad0-3ad820237482.png)

**Comment by x48-crypto** [comment]
@mikheevm I've added the header you suggested to yearn.dev. Currently `x-frame-options` is in-tact. Does that need to change as well? If I remove `x-frame-options` does that mean anyone can load yearn.finance in an iframe? If so that is undesirable. I've reached out to you in discord, please @ me or ping me there so we can debug together when you get a moment. Thanks!

![image](https://user-images.githubusercontent.com/70453354/129110801-b385a0a4-aed6-44da-8d85-aaba17dd68a4.png)

**Comment by x48-crypto** [comment]
Marking this as resolved as @mikheevm has confirmed that this is working as expected now.
